import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "emprestoou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
